version: "3.7"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "5000:5000"
    command: ["flask", "run", "--host=0.0.0.0"]
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    depends_on:
      - backend
    stdin_open: true
    tty: true
  scraper:
    build: ./scraper
    volumes:
      - ./scraper:/app/scraper
    ports:
      - "6800:6800"
    stdin_open: true
    tty: true
    command: ["scrapyd", "--rundir=/app/scraper/scrapyd"]  

  
